### ISSUE TITLE
block.timestamp always 0 when "callcontract"

### ISSUE THREAD

**Issue by hayeah** [qtumproject/qtum#480]
### Describe the issue

`block.timestamp` always 0 when "callcontract"

### Can you reliably reproduce the issue?

yes

#### If so, please list the steps to reproduce below:

Deploy a contract that uses `block.timestamp`:

```
pragma solidity ^0.4.18;

contract BlockTime {

  event BlockTimeEvent(uint256 time);

  // ABI method selector: 87ceff09
  function getBlockTime() constant public returns(uint256) {
    BlockTimeEvent(block.timestamp);
    return block.timestamp;
  }
}
```

Make an RPC call:

```
qcli callcontract a07ae04b78b475bacf747f3a47391af418e1a770 87ceff09
```

The result:

```
{
  "address": "a07ae04b78b475bacf747f3a47391af418e1a770",
  "executionResult": {
    "gasUsed": 22499,
    "excepted": "None",
    "newAddress": "a07ae04b78b475bacf747f3a47391af418e1a770",
    "output": "0000000000000000000000000000000000000000000000000000000000000000",
    "codeDeposit": 0,
    "gasRefunded": 0,
    "depositSize": 0,
    "gasForDeposit": 0
  },
  "transactionReceipt": {
    "stateRoot": "c0d006ca939565b8a5654c8391ca365193f282677510a5a86cc4935523b635fa",
    "gasUsed": 22499,
    "bloom": "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000004000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000
00000004000000000000000000000000000000000000000000",
    "log": [
      {
        "address": "a07ae04b78b475bacf747f3a47391af418e1a770",
        "topics": [
          "834b232e222fd478fbc14dc686a95e5120c477293b9aa05d55cc19491077f49a"
        ],
        "data": "0000000000000000000000000000000000000000000000000000000000000000"
      }
    ]
  }
}
```

### Expected behaviour

`block.timestamp` should be a time that roughly reflects the current time.

It could either just be the local node's time, or network's median blocktime. Personally I think the local node's time more useful for my use case.

### Actual behaviour

The `block.timestamp` is always 0. This makes it hard to use `call` to check some time-related conditions. For example, whether current time has past crowdsale start time.

### What version of Qtum are you using?

```
qtumd --version
Qtum Core Daemon version v0.14.13.0-b4e73b7-dirty
```

**Comment by hayeah** [comment]
A related issue is `block.number`. 

In Ethereum the `block.number` when `callcontract` is the latest block number.

```
pragma solidity ^0.4.18;

contract BlockTime {

  event FooEvent(uint256 time, uint256 blockNumber);

  function emitFooEvent() constant public returns(uint256, uint256) {
    FooEvent(block.timestamp, block.number);
    return(block.timestamp, block.number);
  }
}
```

**Comment by qtum-neil** [comment]
Fixed here: https://github.com/qtumproject/qtum/commit/8e22a5742c6e08cd97e25cafce54b36a1c6e90d7

**Comment by patidarmanoj10** [comment]
@qtum-neil  I am still getting block.timestamp  as 0.    

I am using  
qtumd --version
Qtum Core Daemon version v0.16.2.0-47a3046-dirty

**Comment by qtum-neil** [comment]
@patidarmanoj10 I confirm that bug, will fix in the next release.
Thanks for reporting!

**Comment by qtum-neil** [comment]
Fixed here: https://github.com/qtumproject/qtum/commit/dd6090bc5edb3f0aed1169e42a821b83675d6f05

**Comment by patidarmanoj10** [comment]
@qtum-neil  Thanks for proving fix quickly.  

I understand this was fixed in past also. was it overwritten in some release? I want to download that  version which had fix instead of building it from latest source code because building from source is taking too much time. I am using $docker build --rm -t qtum/qtum:dev .

**Comment by qtum-neil** [comment]
@patidarmanoj10 Yes, the fix was accidentally dropped in a previous release, try version 14.16:

https://github.com/qtumproject/qtum/releases/tag/mainnet-ignition-v0.14.16

A new release including the fix will be made next week.

**Comment by qtum-neil** [comment]
@patidarmanoj10 Yes, the fix was accidentally dropped in a previous release, try version 14.16:

https://github.com/qtumproject/qtum/releases/tag/mainnet-ignition-v0.14.16

A new release including the fix will be made next week.
